export const DEFAULTS = {
  userName: "",
  petKind: "cat",
  renderMode: "pixel",
  theme: "system",
  petName: "",
  accessory: "collar",
  favorites: [],
  routinesEnabled: true,
  musicStyle: "sway",
  quietAuto: true,
  quietFocus: false,
  quietManual: false,
  homeDisplay: "primary",
  homeCorner: "bottom-right",
  spotifyEnabled: false,
  furColor: "#2b2b2b",
  bellyColor: "#f3ead8",
  innerEarColor: "#e59aa4",
  markColor: "#1a1a1a",
  eyeColor: "#f7f7f4",
  pupilColor: "#171717",
  noseColor: "#d77884",
  pattern: "solid",
  scale: 5,
  peekMode: false,
  pinnedMessage: "",
  stretchMinutes: 30,
  waterMinutes: 45,
  pomodoroFocus: 25,
  pomodoroBreak: 5,
  pomodoroEnabled: false,
  reminders: [],
  calendarUrl: "",
  calendarMinutes: 10,
  openAtLogin: false,
  paused: false,
  collarColor: "#6d958d",
  soundEnabled: true,
  agentEnabled: true,
  agentShowOutput: true,
  agentSound: false,
  petLooks: {},
};

export const PETS = [
  { id: "cat", label: "Cat" },
  { id: "dog", label: "Dog" },
];

export const PET_DEFAULTS = {
  cat: {
    furColor: "#a8a8a8",
    bellyColor: "#ffffff",
    markColor: "#5c5c5c",
    innerEarColor: "#f3a8b5",
    noseColor: "#f3a8b5",
    pattern: "tabby",
  },
  dog: {
    furColor: "#c48c48",
    bellyColor: "#ffffff",
    markColor: "#8b5a2a",
    innerEarColor: "#e8b8a0",
    noseColor: "#2a2118",
    pattern: "solid",
  },
};

export const PATTERNS = [
  { id: "solid", label: "Solid" },
  { id: "tabby", label: "Tabby" },
  { id: "tuxedo", label: "Tuxedo" },
  { id: "calico", label: "Calico" },
  { id: "siamese", label: "Siamese" },
  { id: "spotted", label: "Spotted" },
  { id: "cow", label: "Cow" },
];

export const PRESETS = [
  {
    id: "original",
    label: "Original",
    furColor: "#a8a8a8",
    bellyColor: "#ffffff",
    markColor: "#5c5c5c",
    innerEarColor: "#f3a8b5",
    noseColor: "#f3a8b5",
    pattern: "tabby",
  },
  {
    id: "void",
    label: "Void",
    furColor: "#2b2b2b",
    bellyColor: "#f3ead8",
    markColor: "#141414",
    pattern: "solid",
  },
  {
    id: "orange",
    label: "Orange",
    furColor: "#d37a32",
    bellyColor: "#f6e4c4",
    markColor: "#a35216",
    pattern: "tabby",
  },
  {
    id: "gray",
    label: "Gray",
    furColor: "#8b8b8b",
    bellyColor: "#f0ece4",
    markColor: "#5c5c5c",
    pattern: "tabby",
  },
  {
    id: "cream",
    label: "Cream",
    furColor: "#e6d2a8",
    bellyColor: "#fff8ea",
    markColor: "#c9b07a",
    pattern: "solid",
  },
  {
    id: "calico",
    label: "Calico",
    furColor: "#2b2b2b",
    bellyColor: "#f6e4c4",
    markColor: "#d37a32",
    pattern: "calico",
  },
  {
    id: "siamese",
    label: "Siamese",
    furColor: "#efe3cb",
    bellyColor: "#fff8ea",
    markColor: "#5a3b28",
    pattern: "siamese",
  },
  {
    id: "tuxedo",
    label: "Tuxedo",
    furColor: "#222222",
    bellyColor: "#f7f4ee",
    markColor: "#111111",
    pattern: "tuxedo",
  },
];

export const DOG_PATTERNS = [
  { id: "solid", label: "Solid" },
  { id: "saddle", label: "Saddle" },
  { id: "blaze", label: "White blaze" },
  { id: "blacktan", label: "Black & tan" },
  { id: "spotted", label: "Spotted" },
  { id: "patches", label: "Patches" },
];
export const DOG_PRESETS = [
  {
    id: "golden",
    label: "Golden",
    furColor: "#c48c48",
    bellyColor: "#fff0d9",
    markColor: "#895b3a",
    noseColor: "#322b36",
    pattern: "solid",
  },
  {
    id: "biscuit",
    label: "Biscuit",
    furColor: "#e4c998",
    bellyColor: "#fff8e7",
    markColor: "#bd9664",
    noseColor: "#60473e",
    pattern: "solid",
  },
  {
    id: "cocoa",
    label: "Cocoa",
    furColor: "#95654d",
    bellyColor: "#ecd5b4",
    markColor: "#5f4038",
    noseColor: "#322b36",
    pattern: "blaze",
  },
  {
    id: "beagle",
    label: "Beagle",
    furColor: "#c58c50",
    bellyColor: "#fff5de",
    markColor: "#4c3c38",
    noseColor: "#322b36",
    pattern: "saddle",
  },
  {
    id: "collie",
    label: "Collie",
    furColor: "#4c4b52",
    bellyColor: "#faf2df",
    markColor: "#32303b",
    noseColor: "#322b36",
    pattern: "blaze",
  },
  {
    id: "freckles",
    label: "Freckles",
    furColor: "#eee8db",
    bellyColor: "#fffaef",
    markColor: "#60534f",
    noseColor: "#322b36",
    pattern: "spotted",
  },
];
